#!/bin/bash
for testInput in *.txt; do
   name=${testInput%.txt}
   echo $name.txt $name.expect
   #java < $testInput > $name.out
   java MatrixWork <<< "$name.txt" > $name.expect
   echo "======================================="
   cat $name.expect
   #diff -q $name.out $name.expect
done
